Skip unretrievable Remote Images instead of exiting from probe failure
tomoyukikashiro/html2amp pull request #166
Opened 2021-04-27 15:06 UTC by rpong

@tomoyukikashiro , we've been using the PR for some time, hoping this will get your approval. This little tweak skips the unavailable images during amp page generation from the original page, instead of exiting from Probe Failure.

2021-04-28 11:49 UTC, tomoyukikashiro requested changes
@rpong Thank you for you contribution !! 🎉 
I left some comments. plz check them and can you add tests for what you added ??

2021-04-28 11:49 UTC, tomoyukikashiro commented on lib/utils.js
> +        console.log(`Invalid Asset, Skipping....`)
```suggestion
        console.log(`Invalid Asset, Skipping.... (${url})`)
```

2021-04-28 11:49 UTC, tomoyukikashiro commented on lib/utils.js
> +        console.log(`Invalid Asset, Skipping....`)
fore more information to debug 👀

2021-04-28 11:49 UTC, tomoyukikashiro commented on lib/utils.js
> +  if (result != null) {
```suggestion
  if (result !== null) {
```

2021-04-28 11:49 UTC, tomoyukikashiro commented on lib/utils.js
> +    }
```suggestion
  }
```

2021-04-28 11:50 UTC, tomoyukikashiro commented on lib/utils.js
> +    }
it is my fault that I didn't add any lint for this project 🙇

2021-04-28 16:48 UTC, rpong commented
> @rpong Thank you for you contribution !! 🎉
> I left some comments. plz check them and can you add tests for what you added ??

Thank you for these, i merged your suggestions. Will try to add tests for this change within the week.

2021-04-29 17:13 UTC, rpong commented
> @rpong Thank you for you contribution !! 🎉
> I left some comments. plz check them and can you add tests for what you added ??

`Unavailable images are ignored` test added. Thank you @tomoyukikashiro

2021-05-01 12:18 UTC, tomoyukikashiro approved these changes
👍 👍 👍

Thank you for your contribution !!

2021-05-01 12:18 UTC, merged